//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Injectable } from '@angular/core';
import { HttpParams, HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { environment } from 'src/environments/environment';

@Injectable() export class BaseController
{
	constructor (protected http: HttpClient) { } 
}
@Injectable() export class IngredientController
{
	public GetAllIngredients() : Observable<any>
	{
		return this.http.get<any>(`${environment.apiUrl}/Ingredient/GetAllIngredients`,
		{
			responseType: 'json',
			observe: 'response',
		})
		.pipe(map(response => response.body));
		
	}
	public GetProductIngredientsByProductId(id: number) : Observable<any>
	{
		const body = <any>{ 'id': id };
		return this.http.get<any>(`${environment.apiUrl}/Ingredient/GetProductIngredientsByProductId`,
		{
			responseType: 'json',
			observe: 'response',
			params: new HttpParams({ fromObject: body })
		})
		.pipe(map(response => response.body));
		
	}
	public CreateIngredient(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/Ingredient/CreateIngredient`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public UpdateIngredient(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/Ingredient/UpdateIngredient`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public DeleteIngredient(id: number) : Observable<any>
	{
		const body = <any>id;
		return this.http.post<any>(`${environment.apiUrl}/Ingredient/DeleteIngredient`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	constructor (protected http: HttpClient) { } 
}
@Injectable() export class OrderController
{
	public GetAllOrders() : Observable<any>
	{
		return this.http.get<any>(`${environment.apiUrl}/Order/GetAllOrders`,
		{
			responseType: 'json',
			observe: 'response',
		})
		.pipe(map(response => response.body));
		
	}
	public GetActiveOrders() : Observable<any>
	{
		return this.http.get<any>(`${environment.apiUrl}/Order/GetActiveOrders`,
		{
			responseType: 'json',
			observe: 'response',
		})
		.pipe(map(response => response.body));
		
	}
	public CreateOrder(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/Order/CreateOrder`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public UpdateOrder(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/Order/UpdateOrder`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public DeleteOrder(id: number) : Observable<any>
	{
		const body = <any>id;
		return this.http.post<any>(`${environment.apiUrl}/Order/DeleteOrder`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	constructor (protected http: HttpClient) { } 
}
@Injectable() export class ProductController
{
	public GetAllProducts() : Observable<any[]>
	{
		return this.http.get<any[]>(`${environment.apiUrl}/Product/GetAllProducts`,
		{
			responseType: 'json',
			observe: 'response',
		})
		.pipe(map(response => response.body));
		
	}
	public CreateProduct(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/Product/CreateProduct`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public UpdateProduct(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/Product/UpdateProduct`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public UpdateProductVariant(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/Product/UpdateProductVariant`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public DeleteProductVariant(id: number) : Observable<any>
	{
		const body = <any>id;
		return this.http.post<any>(`${environment.apiUrl}/Product/DeleteProductVariant`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public BulkDeleteProductVariants(ids: number[]) : Observable<number[]>
	{
		const body = <any>ids;
		return this.http.post<number[]>(`${environment.apiUrl}/Product/BulkDeleteProductVariants`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public DeleteProduct(id: number) : Observable<any>
	{
		const body = <any>id;
		return this.http.post<any>(`${environment.apiUrl}/Product/DeleteProduct`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	constructor (protected http: HttpClient) { } 
}
@Injectable() export class RoleController
{
	public GetAllRoles() : Observable<any>
	{
		return this.http.get<any>(`${environment.apiUrl}/Role/GetAllRoles`,
		{
			responseType: 'json',
			observe: 'response',
		})
		.pipe(map(response => response.body));
		
	}
	public CreateRole(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/Role/CreateRole`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public UpdateRole(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/Role/UpdateRole`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public DeleteRole(id: number) : Observable<any>
	{
		const body = <any>id;
		return this.http.post<any>(`${environment.apiUrl}/Role/DeleteRole`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	constructor (protected http: HttpClient) { } 
}
@Injectable() export class UserController
{
	public GetAllUsers() : Observable<any>
	{
		return this.http.get<any>(`${environment.apiUrl}/User/GetAllUsers`,
		{
			responseType: 'json',
			observe: 'response',
		})
		.pipe(map(response => response.body));
		
	}
	public CreateUser(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/User/CreateUser`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public UpdateUser(dto: any) : Observable<any>
	{
		const body = <any>dto;
		return this.http.post<any>(`${environment.apiUrl}/User/UpdateUser`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	public DeleteUser(id: number) : Observable<any>
	{
		const body = <any>id;
		return this.http.post<any>(`${environment.apiUrl}/User/DeleteUser`,
		body,
		{
			responseType: 'json',
			observe: 'response'
		})
		.pipe(map(response => response.body));
		
	}
	constructor (protected http: HttpClient) { } 
}
