// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace FastFood.Models;

public partial class FastFoodContext : DbContext
{
    public FastFoodContext()
    {
    }

    public FastFoodContext(DbContextOptions<FastFoodContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Ingredient> Ingredients { get; set; }
    public virtual DbSet<Order> Orders { get; set; }
    public virtual DbSet<Product> Products { get; set; }
    public virtual DbSet<ProductVariant> ProductVariants { get; set; }
    public virtual DbSet<ProductVariantIngredient> ProductVariantIngredients { get; set; }
    public virtual DbSet<ProductVariantOrder> ProductVariantOrders { get; set; }
    public virtual DbSet<Role> Roles { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Ingredient
        modelBuilder.Entity<Ingredient>(entity =>
        {
            entity.ToTable("Ingredient");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        // Order
        modelBuilder.Entity<Order>(entity =>
        {
            entity.ToTable("Order");
            entity.Property(e => e.OrderReceivedDateTime).HasColumnType("datetime");
            entity.Property(e => e.OrderReadyDateTime).HasColumnType("datetime");
            entity.Property(e => e.OrderDeliveredDateTime).HasColumnType("datetime");
            entity.Property(e => e.OrderCancelledDateTime).HasColumnType("datetime");
        });

        // Product
        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Product");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);
        });

        // ProductVariant
        modelBuilder.Entity<ProductVariant>(entity =>
        {
            entity.ToTable("ProductVariant");

            entity.HasKey(pv => pv.Id);

            entity.HasOne(pv => pv.Product)
                  .WithMany(p => p.ProductVariants)
                  .HasForeignKey(pv => pv.Product_FK)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        // ProductVariantIngredient
        modelBuilder.Entity<ProductVariantIngredient>(entity =>
        {
            entity.ToTable("ProductVariantIngredient");

            entity.HasKey(pvi => pvi.Id);

            entity.HasOne(pvi => pvi.ProductVariant)
                  .WithMany(pv => pv.ProductVariantIngredients)
                  .HasForeignKey(pvi => pvi.ProductVariant_FK)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(pvi => pvi.Ingredient)
                  .WithMany(i => i.ProductVariantIngredients)
                  .HasForeignKey(pvi => pvi.Ingredient_FK)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        // ProductVariantOrder
        modelBuilder.Entity<ProductVariantOrder>(entity =>
        {
            entity.ToTable("ProductVariantOrder");

            entity.HasKey(po => po.Id);

            entity.HasOne(po => po.ProductVariant)
                  .WithMany(p => p.ProductVariantOrders)
                  .HasForeignKey(po => po.ProductVariant_FK)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(po => po.Order)
                  .WithMany(o => o.ProductVariantOrders)
                  .HasForeignKey(po => po.Order_FK)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        // Role
        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("Role");
            entity.Property(r => r.Name)
                  .IsRequired()
                  .HasMaxLength(50)
                  .IsUnicode(false);
        });

        // User
        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");
            entity.Property(u => u.Username)
                  .IsRequired()
                  .HasMaxLength(50)
                  .IsUnicode(false);
            entity.Property(u => u.Password)
                  .IsRequired()
                  .HasMaxLength(255)
                  .IsUnicode(false);
        });

        // UserRole
        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.ToTable("UserRole");

            entity.HasKey(ur => ur.Id);

            entity.HasOne(ur => ur.User)
                  .WithMany(u => u.UserRoles)
                  .HasForeignKey(ur => ur.User_FK)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(ur => ur.Role)
                  .WithMany(r => r.UserRoles)
                  .HasForeignKey(ur => ur.Role_FK)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        base.OnModelCreating(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
