// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace FastFood.Models;

public partial class Ingredient
{
    public Ingredient()
    {
        ProductVariantIngredients = new HashSet<ProductVariantIngredient>();
    }

    public int Id { get; set; }
    public int Quantity { get; set; } // ukupna kolicina u magacinu
    public string Name { get; set; }
    public int Unit { get; set; } // 1=gram, 2=ml, 3=komad

    public ICollection<ProductVariantIngredient> ProductVariantIngredients { get; set; }
}