// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace FastFood.Models;

public partial class Order
{
    public Order() 
    {
        ProductVariantOrders = new HashSet<ProductVariantOrder>();
    }

    public int Id { get; set; }
    public DateTime OrderReceivedDateTime { get; set; }
    public DateTime? OrderReadyDateTime { get; set; }
    public DateTime? OrderDeliveredDateTime { get; set; }
    public DateTime? OrderCancelledDateTime { get; set; }
    public int State { get; set; }
    public decimal TotalPrice { get; set; }
    public int OrderNumber { get; set; }

    public ICollection<ProductVariantOrder> ProductVariantOrders { get; set; }
}