// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace FastFood.Models;

public partial class Product
{
    public Product()
    {
        ProductVariants = new HashSet<ProductVariant>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    public ICollection<ProductVariant> ProductVariants { get; set; }
}