// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace FastFood.Models;

public partial class Role
{
    public Role()
    {
        UserRoles = new HashSet<UserRole>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; }
}