// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FastFood.Models
{
    public partial class Stock
    {
        public Stock()
        {
            Ingredients = new HashSet<Ingredient>();
        }

        public int StockID { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }

        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
}